version: '3'

services:

  app:
    build:
      context: .
    container_name: app
    entrypoint: wait-for database:3306 -t 40 -- ./start.sh
    volumes:
      - ./src:/home/node/app
    depends_on:
      - database
    networks:
      - node-network

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
